### ISSUE TITLE
OBCT，TMGRの細々した改善

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#124]
## 概要
OBCT，TMGRの細々した改善

## 詳細
- [x] doxygenコメントのない連中のコメント追記
- [x] testの追加（ないものは）
- [x] `time_manager.c` でコマンド関数はファイル末にまとめたい
- 規約修正
  - [x] https://github.com/ut-issl/c2a-core/pull/116#discussion_r772514713
  https://github.com/ut-issl/c2a-core/blob/827ea25f8467d9bab09d28e68c6a91f3b317a287/System/TimeManager/time_manager.h#L26-L27
  - [x] `master_clock_` , `OBCT_unixtime_info_` の変数名。というか，これら， `TimeManager` 構造体つくってまとめてもいいのでは？ と言う気がしてる（そっちのほうがC2Aっぽい & UTL 実装時に情報（時刻originとか）をここでもてる？）
- [x] Cmd引数の取得方法を https://github.com/ut-issl/c2a-core/pull/70 に準拠 
- [x] stepが100以上なのおかしくない？
  - https://github.com/ut-issl/c2a-core/blob/5a796cada870a51762555e5edb701a6dcdb1b9e8/Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py#L53
- [x] https://github.com/ut-issl/c2a-core/blob/5a796cada870a51762555e5edb701a6dcdb1b9e8/System/TimeManager/obc_time.h#L29
  - `double unixtime_at_ti0; //!< 観測情報から計算した master_clock が {0, 0, 0} の時の unixtime` ？

## close条件
終わったら

## 備考
- https://github.com/ut-issl/c2a-core/pull/116 からの派生
- からなずしも１つのPRでやる必要はない

@chutaro 頼んだ！

**Comment by chutaro** [comment]
> `TimeManager`構造体つくってまとめてもいいのでは？

これは、`ObcTime`構造体と`OBCT_UnixtimeInfo`構造体を`TimeManager`のメンバーとして持たせるという意味ですか？それとも解体してTimeManagerにまとめるという意味ですか？

**Comment by meltingrabbit** [comment]
`ObcTime`構造体と`OBCT_UnixtimeInfo`構造体の定義は引き続き obct.hで持つのでいいと思う．これは汎用データ型なので，ここで定義すべき．

で，tmgr.hの
https://github.com/ut-issl/c2a-core/blob/94e228155c9f964cf3a5199c5b010f0371c48cd2/System/TimeManager/time_manager.h#L7-L11
を

```
typedef struct
{
  ObcTime master_clock_;
  OBCT_UnixtimeInfo unixtime_info_;
  utl_unixtime_origin_;   // UTL cmd実装時にここに追加
  struct
  {
    ObcTime initializing_time;
    uint8_t initializing_flag;
  } init_info_;
  
} TimeManager;
```

な感じにすればいいのでは？とおもってる

**Comment by chutaro** [comment]
なるほどです！

**Comment by meltingrabbit** [comment]
@chutaro https://github.com/ut-issl/c2a-core/pull/130 がマージされたので，そこで終わったものは，issue descriptionのチェックボックス，更新しておいて～

**Comment by chutaro** [comment]
TMGR に関してのテストは追加し終わったので Closeする。UTL_cmdに関するテストは以下の別issueで
- https://github.com/ut-issl/c2a-core/issues/175
