### ISSUE TITLE
バージョニングをSemantic Versioningに適合させる

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#141]
## 概要
バージョニングをSemantic Versioningに適合させる

## 詳細
 過去のtagも追加で直したい．

## close条件
適合したら

**Comment by sksat** [comment]
C2Aは既に `<major>.<minor>.<patch>`になってません？

**Comment by meltingrabbit** [comment]
なってるね．
major，minor，patchのアップデートルールをきめて，docsに書くまでやってcloseしますか．

**Comment by sksat** [comment]
それでよさそう

**Comment by meltingrabbit** [comment]
https://github.com/ut-issl/c2a-core/blob/develop/Docs/General/release.md に書いた．
