### ISSUE TITLE
TLCDのリファクタ

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#164]
## 概要
TLCDのリファクタ

## 詳細
古いコードなのでリファクタしたい

## close条件
きれいになったら

## 備考
関連
- https://github.com/ut-issl/c2a-core/issues/125
- https://github.com/ut-issl/c2a-core/issues/129

**Comment by chutaro** [comment]
ある程度リファクタしてpytestも追加したのでclose
