### ISSUE TITLE
バージョン情報の記載のあるheaderを作る

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#170]
## 概要
バージョン情報の記載のあるheaderを作る

## 詳細
```
#define C2A_CORE_VER_MAJOR 3
#define C2A_CORE_VER_MINOR 4
#define C2A_CORE_VER_PATCH 0
```

みたいな

## close条件
できたら

## 備考
議論点は

- どのフォルダに配置する？
- いつどのように更新する？

## 関連
- https://github.com/ut-issl/c2a-core/issues/169

**Comment by sksat** [comment]
場所的には `c2a_core_main.h`では，と思っています(何にも属していないのでルートにあるのが望ましい & ルート直下のファイルを増やしたくない)

**Comment by meltingrabbit** [comment]
バージョンしか書かれてないヘッダのほうが，toolなどで読んだときとか，自動で値更新するとき（があるかわからんが）に便利そうって思ったりはした．（あと，適当な場所で使うときにincludeするときとかもわかりやすい．バージョン番号つかうのだけに `c2a_core_main.h` をincludeしたくないなと．）

**Comment by meltingrabbit** [comment]
> ルート直下のファイルを増やしたくない

はそうなので，一旦それで，で，今後困ったらファイル分割するか～

**Comment by sksat** [comment]
toolで読む時，自動更新は別にどこにあってもそんなに変わらないかな，と思っています．
ただ，バージョン番号使うためだけに `c2a_core_main.h`をincludeしたくない，はかなりあると思っていて，個人的にはファイル分けたいですね．ルート直下にファイル増えることを許容できるか次第．

**Comment by meltingrabbit** [comment]
> バージョン番号使うためだけに

実際，これはほぼなさそう．commit hashはtlmにいれたり，デバッグ表示にいれたりするので使うけど

**Comment by sksat** [comment]
そうなんですよね．そんなにプログラム中で使う気はしないというのはある．

**Comment by meltingrabbit** [comment]
じゃあ一旦 `c2a_core_main.h` で．

あとはどう更新するかか．main update prでもいいが，そうするとmain mergeではじめて上がった記載ファイルをどうdevまで持ってくるかが課題．

これ，devをmain merge後に毎回rebaseするのってどうなんだ？（まあいいのかな）

**Comment by meltingrabbit** [comment]
dev rebase って，PRでできるのか，というのも気になり

**Comment by sksat** [comment]
> dev rebase って，PRでできるのか，というのも気になり

これ何を気にしてます？

**Comment by meltingrabbit** [comment]
手元でのforce pushにならない？って．（devとmainはいまforce push禁止してる

**Comment by meltingrabbit** [comment]
あー，ff mergeのpr出せばいいのか？

**Comment by meltingrabbit** [comment]
といってもいま，repository設定で--no-ffマージしか許されていない

**Comment by sksat** [comment]
そうだった... > force push/--no-ff

**Comment by sksat** [comment]
じゃあmain update PRでやればいいのでは

**Comment by meltingrabbit** [comment]
> じゃあmain update PRでやればいいのでは

あーーー，頭がついてなかった．

そっか，main update prってdevにcommitできるじゃん．

**Comment by sksat** [comment]
実はそう

**Comment by meltingrabbit** [comment]
あれ，devはpush禁止してるので，commitできない説

**Comment by sksat** [comment]
アッ

**Comment by meltingrabbit** [comment]
- devのバージョンあげますPR（すぐmain updateするよ `. |ω・)ﾁﾗ`
- main update PR

の2段？？．．．

**Comment by sksat** [comment]
dev push解禁しない限りそれしかないかあ

**Comment by meltingrabbit** [comment]
厳密にはtagよりも古いcommitにバージョン含まれちゃうが，まあ動作に影響のあるファイルには更新ないので，いいか．

**Comment by meltingrabbit** [comment]
ではそれで行くかぁ．

https://github.com/ut-issl/c2a-core/issues/169 とあわせて，リリースフロー，ドキュメント化します．

**Comment by sksat** [comment]
> dev push解禁はないなぁ

ですよねー．adminだけpush可みたいなかんじにできればまた別なんですが．

**Comment by meltingrabbit** [comment]
まあ，それもそれで事故こわいんで，一旦これで運用しよう，でクソだるかったらadmin解禁含めて考えよう．

**Comment by sksat** [comment]
人間ではなくリリース担当Botを生やしてそいつにやらせる，などはないではない(が，運用コストを考えるとノーチャンな気がする)

**Comment by meltingrabbit** [comment]
https://github.com/ut-issl/c2a-core/blob/develop/Docs/General/release.md でやった．


更新については，やってみてだるかったらまた考える．

close．
