### ISSUE TITLE
Discussionsをつくるか，つくるならどう運用するかを考える

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#173]
## 概要
Discussionsをつくるか，つくるならどう運用するかを考える

## 詳細
S2Eは，宣伝したときの問い合わせや細かい質問用につくった．C2Aでどうするか考える．

## close条件
考えたら

**Comment by sksat** [comment]
作っておく分には悪くないのではないかなと思います．結局のところコミュニティ形成の話になっちゃうので運用方法もやりながらでしか決められないし．

**Comment by meltingrabbit** [comment]
つくった．

https://github.com/ut-issl/c2a-core/discussions/177
