### ISSUE TITLE
UTL cmd のテスト対応

### ISSUE THREAD

**Issue by chutaro** [ut-issl/c2a-core#175]
## 概要
UTL cmd のテストを整備する

## 詳細
- https://github.com/ut-issl/c2a-core/issues/64 の続き
- ToDo
  - [x] python-wings-if で UTL cmd を打てるようにする
    - https://github.com/ut-issl/python-wings-interface/pull/6
  - [x] testの追加
    - https://github.com/ut-issl/c2a-core/pull/182
  - [x] wingsで UTL cmd 引数が0.1秒精度に改修されたら pytest も対応させる
  - [x] 実行unixtime < unixtime_at_ti0 の場合を追加
  - [x] update_unixtime をSH.TIを使って行い、現実に寄せる

## close条件
上記が完了したら。

**Comment by meltingrabbit** [comment]
## テストの残り
- https://github.com/ut-issl/c2a-core/pull/182 の残
  - https://github.com/ut-issl/c2a-core/blob/69b265402fbf19f84aa7affd663a2a929afac857/Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py#L220
  - https://github.com/ut-issl/c2a-core/blob/69b265402fbf19f84aa7affd663a2a929afac857/Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py#L112-L121
    - ここは，10個も登録する必要はないし，TL Tlmを見るより，Cmd登録時に `PH_TLC_PAST_TIME` が出てることを確認すべき

**Comment by chutaro** [comment]
完了したのでclose
