### ISSUE TITLE
BCE関連のコマンドの接頭辞がBCTのままなので直す

### ISSUE THREAD

**Issue by yngyu** [ut-issl/c2a-core#220]
## 概要
BCE関連のコマンドの接頭辞がBCTのままなので直す

## 詳細
BCE関連のコマンドの接頭辞が過去のBCTのまま放置されているのでBCEに直す

## close条件
直ったら

**Comment by meltingrabbit** [comment]
これ，それなりに早めが良い気がするので， priority::medium にしておくね

**Comment by yngyu** [comment]
というか今やります、conflict はしない気がするので

**Comment by yngyu** [comment]
https://github.com/ut-issl/c2a-core/pull/221  
マージされたのでclose
