### ISSUE TITLE
ビルドCI Actions の job nameが同じで，branch protectionで区別できない

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#30]
## 概要
ビルドCI Actions の job nameが同じで，branch protectionで区別できない

## 詳細
どっちも build_minimum_user になってるので．

https://github.com/ut-issl/c2a-core/blob/62e835382a108c6ec688c798d4b918e8ad28b598/.github/workflows/build_as_c89.yml#L18-L19

## close条件
- [ ] 名前をユニークにしたら
- [ ] branch_protection_rules を再設定したら

**Comment by sksat** [comment]
これworkflowじゃなくてjobの名前なのかなり非自明ですね

**Comment by meltingrabbit** [comment]
それな～～～～ workflow nameにしてほしすぎる．

**Comment by sksat** [comment]
まあjobを区別できるのは便利かもしれないですが，しかしなあ．
やるにしても"workflow.job"みたいなかんじになっててほしさある．GitHubにfeedback送るべき案件かもしれない．

**Comment by meltingrabbit** [comment]
https://github.com/github/feedback/discussions これか？

**Comment by sksat** [comment]
ここもある
https://support.github.com/contact/feedback

**Comment by meltingrabbit** [comment]
送った．

**Comment by meltingrabbit** [comment]
https://github.com/ut-issl/c2a-core/pull/31 のとおり，なんと branch protection rule で設定したものが全部パスしないとマージできないとかいうシロモノだった．

なので，最後のcommitが指定したCIすべてを回すもので，かつすべて通らないと，マージできなくなってしまう．．．

**Comment by meltingrabbit** [comment]
とはいえ，一旦job nameのコンフリクトは解消されたのでcloseする．
