### ISSUE TITLE
DB の差分表示をマシにする方法を考える

### ISSUE THREAD

**Issue by yngyu** [ut-issl/c2a-core#306]
## 概要
DB の差分表示をマシにする方法を考える

## 詳細
現状 DB の差分表示が割と酷いことになっているので、それをどうにかしたい  
https://github.com/ut-issl/c2a-core/pull/287/files#diff-6057a578cd9fe3f06d11e49a2542bbafb49d2064d4a102c4ff3b28dfa2135dfb  
このプルリクとか

## close条件
差分が見やすくなったら

**Comment by meltingrabbit** [comment]
ましになった！！！わーい！！！！
