### ISSUE TITLE
CCP_form_xxx で，パケット配送までまとめてやってほしい

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#313]
## 概要
CCP_form_xxx で，パケット配送までまとめてやってほしい

## 詳細
```
  CCP_form_tlc();
  PH_analyze_cmd_packet();
```
を
```
CCP_register_tlc
```
にまとめた関数をつくりたい

## close条件
できたら

## 備考（関連）
- https://github.com/ut-issl/c2a-core/issues/296#issuecomment-1083889739
- https://github.com/ut-issl/c2a-core/issues/283#issuecomment-1069787479
- https://github.com/ut-issl/c2a-core/pull/299 より前にやったほうがいいかも？

**Comment by yngyu** [comment]
https://github.com/ut-issl/c2a-core/pull/320 でマージされたので close
