### ISSUE TITLE
testをいれる

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#34]
## 概要
testをいれる

## 詳細
pytestで書かれたやつ．

どこにどのように入れるかも議論する．

## close条件
いれたら

**Comment by meltingrabbit** [comment]
https://github.com/ut-issl/c2a-core/issues/33 を議論していて思ったけれども，testも同じリポジトリ（userならそのuser-repositry/test，coreのcore部分なら c2a-core/test/）でいいのでは？と思ってきた．

今までは，リポジトリを分けていた（hoge_mobc_pytest リポジトリがあった）けれど，不要？

**Comment by meltingrabbit** [comment]
を議論していて思ったけれども，testも同じリポジトリ（userならそのuser-repositry/test/，coreのcore部分なら c2a-core/test/）でいいのでは？と思ってきた．

今までは，リポジトリを分けていた（hoge_mobc_pytest リポジトリがあった）けれど，不要？

**Comment by sksat** [comment]
テストはむしろ本体にくっついていないと微妙まである

**Comment by meltingrabbit** [comment]
CIつくってて，びみょいなと実感してるところだった．（CI側でバージョンの一致が辛くなってた）

**Comment by meltingrabbit** [comment]
> coreのcore部分なら c2a-core/test/

これはだめだな．coreのパラメタはuser側で設定されるので，core開発用のcoreのテストはcoreのminimum user に入れる必要があるな．

**Comment by meltingrabbit** [comment]
テストCIは https://github.com/ut-issl/c2a-core/issues/16 で引き継ぐ
