### ISSUE TITLE
src_user/IfWrapper/Silsに.cなC++のソースファイルがあってよくない

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#36]
## 概要
src_user/IfWrapper/Sils/*.c にC++のコードを置くことについて議論する

## 詳細
- https://github.com/ut-issl/c2a-core/pull/35 でいろいろ話が出た
- これらはCとしてもC++としてもビルドされる，というわけではなく，C++としてしかビルドされない(SILS専用)
- それにも関わらず拡張子が`.c`になっており非常に分かりにくい
- さらに，CMakeでビルドする上でも都合が悪そう

## close条件
なんとなく今後の方向性が見えてきたら．

**Comment by sksat** [comment]
流石に分かりにくいのでC++っぽい拡張子にしましょう．S2Eと合わせるなら`.cpp`か．

**Comment by sksat** [comment]
https://github.com/ut-issl/c2a-core/pull/35#issuecomment-979321172
ファイル名が変わるのでS2Eも困るからタスク切った方がいいな，と思ったけど，これはよく考えたらS2Eの`CMakeLists.txt`が **すごいことになってる** ことによるものであって，向こうの`CMakeLists.txt`も直したら一瞬で解決する問題だった．

**Comment by sksat** [comment]
区別したいという元の気持ちからするとC++なヘッダは`.hpp`とかにしたい気もするが，S2Eのヘッダは普通に`.h`なのよな

**Comment by meltingrabbit** [comment]
> .cpp, .hpp

これはそうんだね．そうすべきだとおもう．

**Comment by sksat** [comment]
まあS2Eと一貫性が無くなるだけ(どうせこれをincludeするのもS2Eだけ)なので，区別できるようにするのを優先して`.hpp`にしてもいい気がするな．

**Comment by sksat** [comment]
> [#35 (comment)](https://github.com/ut-issl/c2a-core/pull/35#issuecomment-979321172) ファイル名が変わるのでS2Eも困るからタスク切った方がいいな，と思ったけど，これはよく考えたらS2Eの`CMakeLists.txt`が **すごいことになってる** ことによるものであって，向こうの`CMakeLists.txt`も直したら一瞬で解決する問題だった．

よく考えたらこれはなんも困らなかった．include pathの指定が渋いだけなので．

**Comment by sksat** [comment]
置くことについて議論する，というより既にそうなっていて非常にわかりにくい上に #35 で実用上の問題も発生している，といった状態なのでタイトル変えるか
