### ISSUE TITLE
EH で BC 展開時に時間調整が発生したときのエラー扱いを再考する

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#389]
## 概要
EH で BC 展開時に時間調整が発生したときのエラー扱いを再考する

## 詳細
- https://github.com/ut-issl/c2a-core/blob/cfd7781e8716cd7b4597c6ff746f9c3db1e7691a/System/EventManager/event_handler.c#L653-L660
  - BC展開エラーはhighでいいが，時間調整はlowでもいい？
- https://github.com/ut-issl/c2a-core/blob/cfd7781e8716cd7b4597c6ff746f9c3db1e7691a/Applications/timeline_command_dispatcher.c#L277-L286
  - どうしましょう？

## close条件
考えて修正したら

**Comment by meltingrabbit** [comment]
@chutaro １個めだけど，cmd返り値が現状とれないので，

- https://github.com/ut-issl/c2a-core/issues/376

が終わらないと対応できないかも．

**Comment by chutaro** [comment]
そうなんですよね。

PL_deploy_block_cmd の方で EL 登録しても良いのかなとは思いました（bc_id を note にすればどのタイミングで発生したのかもなんとなく分かると思うので）
