### ISSUE TITLE
pytestのWINGSの認証情報を環境変数で渡せるようにする

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#44]
## 概要
testのWINGSの認証情報を環境変数で渡せるようにする

## 詳細
jsonで渡すのが渋いので．

## close条件
できたら

## 備考
Windowsでの環境変数の取り扱いがいまいちで，ぱっといい方法がわからない．

Linuxなら
```
HOGE=hoge pytest
```
でいいんだけど．

**Comment by yngyu** [comment]
マージされたので close
