### ISSUE TITLE
TLM_MGR で DR再生とDR記録も扱えるようにする

### ISSUE THREAD

**Issue by chutaro** [ut-issl/c2a-core#455]
## 概要
TLM_MGR で DR再生とDR記録も扱えるようにする

## 詳細
あるユーザー部で必要になり雑に実装したが、DR関連も組み込めるようになった代わりにSYSTEMテレメとUSERテレメを分ける機能を削ってしまったので、地上試験だと使いにくい。

そもそも core にある機能を user 部でアレンジして持ってるのも変なので、coreの方に以下の機能を追加したい。一方で、現状DRはcore機能ではなくuser選択制なので、むずい。
- DR再生とDR記録も TL_tlm で管理できるようにする

プラスで、使うOBC次第だとは思うが
- テレメ組み換えの内容を MRAM などの不揮発メモリに保存できるようにしたい
- 3-3アノマリを消す

## close条件
どうなったらcloseできるか

## 備考
なにかあれば

**Comment by meltingrabbit** [comment]
- https://github.com/ut-issl/c2a-core/issues/247 で tlm mgr が一度ぶっ壊れることが確定してるので，その時に一緒にやりたいね

**Comment by chutaro** [comment]
新tlm mgr が実装されたのでクローズ
