### ISSUE TITLE
sub OBC のテレメを generate する便利コマンドを追加する

### ISSUE THREAD

**Issue by chutaro** [ut-issl/c2a-core#481]
## 概要
sub OBC のテレメを generate する便利コマンドを追加する

## 詳細
現状、sub OBC で generate してから MOBC で generate する必要がある。それをセットにしたコマンドがあってもいい。引数は APID と Cmd_id

## close条件
作ったら

## 備考
なにかあれば

**Comment by meltingrabbit** [comment]
- https://github.com/ut-issl/c2a-core/issues/247 のあとにやるぞ！！！（博論．．．．）

**Comment by chutaro** [comment]
やりましょう！

**Comment by meltingrabbit** [comment]
とはいえ，運用のこと考えると，MOBCへは1Hzで来てほしいけど，GSまで1Hzで来たら困るよね．

1shot用みたいな雰囲気か？

**Comment by chutaro** [comment]
1shot を想定していました。今だと毎回2コマンド送る必要があって面倒ですね

**Comment by meltingrabbit** [comment]
理解．良さそう

**Comment by chutaro** [comment]
メモ
- 2nd obc の TG のコマンドID が必要
- cmd の apid と tlm の apid 両方必要なのを失念していた
- 色々大変なので、実運用も考えて、user側にコマンドを持った方が良いと思った
  - Cmd_TG_generate_AOBC_tlm(AOBCのtlm id)
  - Cmd_TG_generate_XOBC_tlm(XOBCのtlm id)
  - etc
