### ISSUE TITLE
black や flake8 などのバージョンを全リポジトリで統一管理できるように reusable workflow にする

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#495]
## 概要
black や flake8 などのバージョンを全リポジトリで統一管理できるように reusable workflow にする

## 詳細
- https://github.com/ut-issl/c2a-core/issues/491 のつづき
- https://github.com/ut-issl/c2a-core/issues/491#issuecomment-1434038409

## close条件
できたら

**Comment by sksat** [comment]
一応確認: 実際こういった reusable workflow を一番使うのもメンテするのも AE なので，実装場所は https://github.com/arkedge/workflows-c2a ということでよいですよね？

**Comment by meltingrabbit** [comment]
OK

**Comment by sksat** [comment]
基本的には各リポジトリでバージョン固定して管理すべき．なんらかの方法で一元管理してその一元管理しているもののバージョンを各リポジトリでは管理するようにしてもよいが，black と flake8 だけであればあまりラクにはならないし，やるとしても reusable workflow という手段は取らない．
