### ISSUE TITLE
Examples の名前が紛らわしいので変える

### ISSUE THREAD

**Issue by sksat** [ut-issl/c2a-core#531]
## 概要
Examples の名前が紛らわしいので変える

## 詳細
- minimum user は「ビルド・実行できる最小限の C2A コードセット」ではなく，MOBC C2A user のサンプル実装
- `Examples/` 以下に突っ込むのは自明に C2A user となるので，`_user` suffix は不要そう
- `Examples/README.md` とかあるとよさそう

**Comment by meltingrabbit** [comment]
一番でかい違い

defaultのupsteramが
- minimum user: space packet on transfer frame
- 2nd obc sample: space pacekt on eb90 frame

あとメモリ使用量や，gs cmd packet 配送周りの inital TL の組み方が違う．

**Comment by sksat** [comment]
v4 でやった: https://github.com/arkedge/c2a-core/issues/7
