### ISSUE TITLE
Housekeeping Telemetry，Mission Telemetry という命名をなんとかしたい

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#552]
## 概要
Housekeeping Telemetry，Mission Telemetry という命名をなんとかしたい

## 詳細
- 歴史的経緯で，テレメのキューイングで２種あった．
- 現在は MS TLM ばかり使われてる

## close条件
方針きまったら

## 備考
https://github.com/ut-issl/c2a-core/pull/541#discussion_r1171304622 ででた

**Comment by chutaro** [comment]
これなんですが、
- TG_GENERATE_HK_TLM（1s周期とかで常時降ろすテレメ、というのを明示的に言いたいときに使う）
- TG_GENERATE_RT_TLM（今まで MS_TLM だったやつ。リアルタイムで降ろすテレメという意図。通常こっちを使う）

でどうでしょうか？次回の core mtg で相談したいです。

**Comment by meltingrabbit** [comment]
> Mission Telemetry

Realtime Telemetry

> Housekeeping Telemetry

？？

**Comment by meltingrabbit** [comment]
ここで Real time とやってしまうと，

Mission (Realtime) & Housekeeping がともに Realtime となってしまい，非常に confusing
