### ISSUE TITLE
[新テレメ配送] Tlm Manager の 新 GENERATE_TLM 対応

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#556]
## 概要
[新テレメ配送] Tlm Manager の 新 GENERATE_TLM 対応

## 詳細
全面的に作り直し

**Comment by meltingrabbit** [comment]
今
```
Cmd_TLM_MGR_REGISTER_HK_TLM
Cmd_TLM_MGR_REGISTER_SYSTEM_TLM
Cmd_TLM_MGR_REGISTER_HIGH_FREQ_TLM
Cmd_TLM_MGR_REGISTER_LOW_FREQ_TLM
```

新
```
Cmd_TLM_MGR_REGISTER_GENERATE_TLM
Cmd_TLM_MGR_REGISTER_FORWARD_TLM
Cmd_TLM_MGR_REGISTER_REPLAY_TLM
Cmd_TLM_MGR_REGISTER_STORED_TLM
```

引数が
```
（APID） for forward
tlm id
partiton for stored
種別（hk or system or high / low freq）
```

追加機能として

- 座標指定で上書きできるように
- 現在の状況がパッと分かるようなtlm view

**Comment by meltingrabbit** [comment]
@chutaro 

これ，
```
Cmd_TLM_MGR_REGISTER_GENERATE_TLM 1 1 tlm_id
```
みたいなので上書きしたい，といってたけど，やっぱり試験で 1 1 みたいな座標指定したくないし，管理もしたくないので，
上書きを
```
Cmd_TLM_MGR_DELETE_GENERATE_TLM tlm_id_A
Cmd_TLM_MGR_REGISTER_GENERATE_TLM tlm_id_B
```
みたく設計しようとしています．
そうすると，終始user側は座標意識せずにtlmの差分だけ組み換え可能．

この方針でよいですか？

```

**Comment by chutaro** [comment]
良いと思います！
- 追加するときは、なるべく登録が少ないBCを選ぶ
- 削除するときは tlm id で検索してテキトーな場所を消す（追加するときに満遍なくをケアしていればテレメ詰まりとかは予防できるはず？）

**Comment by chutaro** [comment]
というか、delete のときは頻度指定は無くて、該当する tlm id は全部消す感じですかね？（5Hzぶん登録してあっても、0Hzにする）

**Comment by chutaro** [comment]
あと若干ずれるんですが、DRはユーザー定義ですが、設定すれば tlm mgr でも store と replay が使えるようになる、って感じでしょうか？

**Comment by chutaro** [comment]
あとこれも個人的意見ですが、HKとSYSTEMは分けなくても良いかなと思います

**Comment by meltingrabbit** [comment]
> あと若干ずれるんですが、DRはユーザー定義ですが、設定すれば tlm mgr でも store と replay が使えるようになる、って感じでしょうか？

これめっちゃしたいので，方針は

- DR を core で実装する（ほんとうはこれがいい）
- DRの再生cmd名だけcoreで定義してしまって，一旦はDRはuserでもつ

のどっちか

**Comment by chutaro** [comment]
> いや，system or hk or high or low は指定して，そのなかから１つだけ消します．
で，消したら，またまんべんになるように，最も後ろに登録されてるtlmを消したところに差し込みます．

なるほどです！そう実装できるならそっちの方がよいですね

**Comment by meltingrabbit** [comment]
結局抽象化するので，種類は何個でも実装コストは変わらないのよね < HK, system

**Comment by chutaro** [comment]
> HK, system

機能としては同じ（1Hzで、clear user しても消えないテレメ）なので、一つでいいかなと思いました。実装コスト変わらないかもですが、使用するBCが圧迫されたりしませんかね？例えば、hkと system 用に2個BC使っちゃうと、残り8個で、ユーザー登録の高頻度低頻度の自由度が減っちゃうみたいな

**Comment by meltingrabbit** [comment]
じゃあ、そこuser設定にしますか。

**Comment by meltingrabbit** [comment]
試験時は HK と system が欲しくて，運用時はもはや HK と systemどっちもいらない or HKだけほしい，などの説がある

**Comment by chutaro** [comment]
> 運用時は very lowがほしい

たしかにそうですね。BCのrotatorの設定で何cycleごとに実行されるか、みたいなのはありましたが、そうするとその列が全部 very low になってしまってちょっともったいないですね

本当にvery low でいいやつは TL1で別途60s周期とかで回すしかないですかね（テレメ詰まりには影響ほぼないので）

**Comment by meltingrabbit** [comment]
systemを組み替えるときにHKとめなくないから、っておもってたけど、delできるなら、systemいらない。。。？

**Comment by chutaro** [comment]
> systemを組み替えるときにHKとめなくないから、っておもってたけど、delできるなら、systemいらない。。。？

なるほどです。僕はまとめる派です！（ただ実装しててやっぱり、みたいなのもあると思うのでお任せします）

**Comment by meltingrabbit** [comment]
OK．

HK, system まとめます．
で，まとめると，user tlmという枠組みわかりにくいのでなくします（消す時は high, low どっちも個別にけしてもらう）

**Comment by meltingrabbit** [comment]
@chutaro 

DR 再生は `Cmd_DR_REPLAY_TLM` にしようと思います．

引数は
u8 dr_partition
u8 dest_info
u8 dump_num

ですが，
dump_num = 1
dest_info = CTP_DEST_FLAG_RP
に制限していいですよね？（dump num は generate も 1 に制限してる．dest info は，DR 再生したものを，再び DR に書き戻したい，とかがなければ，このままでいいと思ってます．）

**Comment by meltingrabbit** [comment]
@chutaro あともう１つ．

2nd obc へのtlm要求は tlm mgr の管轄外，でいいですよね？（forwardはもちろんするが，2nd obcへのgenerate要求はしない）

2nd obcのtlm送出は，2nd obcで管理してもらうということで（2nd obc→MOBCは高頻度でもいいし．つまり2nd obc→MOBCは送られるが，MOBC→GSには送られないものが会っても良いので）

**Comment by meltingrabbit** [comment]
コマンド，結局こうなったな．．．

```
Cmd_TLM_MGR_REGISTER_GENERATE_TLM_AS_HK
Cmd_TLM_MGR_REGISTER_GENERATE_TLM_AS_HIGH_FREQ
Cmd_TLM_MGR_REGISTER_GENERATE_TLM_AS_LOW_FREQ
Cmd_TLM_MGR_REGISTER_FORWARD_TLM_AS_HK
Cmd_TLM_MGR_REGISTER_FORWARD_TLM_AS_HIGH_FREQ
Cmd_TLM_MGR_REGISTER_FORWARD_TLM_AS_LOW_FREQ
Cmd_TLM_MGR_REGISTER_STORED_TLM_AS_HK
Cmd_TLM_MGR_REGISTER_STORED_TLM_AS_HIGH_FREQ
Cmd_TLM_MGR_REGISTER_STORED_TLM_AS_LOW_FREQ
Cmd_TLM_MGR_REGISTER_REPLAY_TLM_AS_HK
Cmd_TLM_MGR_REGISTER_REPLAY_TLM_AS_HIGH_FREQ
Cmd_TLM_MGR_REGISTER_REPLAY_TLM_AS_LOW_FREQ

Cmd_TLM_MGR_DELETE_GENERATE_TLM_AS_HK
Cmd_TLM_MGR_DELETE_GENERATE_TLM_AS_HIGH_FREQ
Cmd_TLM_MGR_DELETE_GENERATE_TLM_AS_LOW_FREQ
Cmd_TLM_MGR_DELETE_FORWARD_TLM_AS_HK
Cmd_TLM_MGR_DELETE_FORWARD_TLM_AS_HIGH_FREQ
Cmd_TLM_MGR_DELETE_FORWARD_TLM_AS_LOW_FREQ
Cmd_TLM_MGR_DELETE_STORED_TLM_AS_HK
Cmd_TLM_MGR_DELETE_STORED_TLM_AS_HIGH_FREQ
Cmd_TLM_MGR_DELETE_STORED_TLM_AS_LOW_FREQ
Cmd_TLM_MGR_DELETE_REPLAY_TLM_AS_HK
Cmd_TLM_MGR_DELETE_REPLAY_TLM_AS_HIGH_FREQ
Cmd_TLM_MGR_DELETE_REPLAY_TLM_AS_LOW_FREQ
```

**Comment by chutaro** [comment]
> user tlmという枠組みわかりにくいのでなくします（消す時は high, low どっちも個別にけしてもらう）

こうすると hk, high ,low で分ける意味もなくなっちゃいませんか？hk 以外をまとめて消す機能はあっても良いと思います。

**Comment by chutaro** [comment]
> DR 再生は Cmd_DR_REPLAY_TLM
dump_num = 1
dest_info = CTP_DEST_FLAG_RP に制限

はい、良いと思います

**Comment by meltingrabbit** [comment]
> こうすると hk, high ,low で分ける意味もなくなっちゃいませんか？hk 以外をまとめて消す機能はあっても良いと思います。

OK


NOPうめが重いので，3-3でちゃうけど，つくっておきます

**Comment by chutaro** [comment]
> 2nd obc へのtlm要求は tlm mgr の管轄外，でいいですよね？（forwardはもちろんするが，2nd obcへのgenerate要求はしない）
2nd obcのtlm送出は，2nd obcで管理してもらうということで

これなんですが、2nd obc の BC が枯渇して、2nd obc で新たに1Hzでテレメ回すのが難しい、みたいな事象が起きたんですよね。

2nd obc 側で、1Hz テレメ生成用の BC はあらかじめ確保しておく、で対応、って感じですかね。。

**Comment by meltingrabbit** [comment]
まじかいな．．．

DS改修でメモリふえたから頑張って欲しい．．．．

**Comment by chutaro** [comment]
コマンド多いっすね、、

あと思ったのですが、sub OBC のテレメを DR に記録する場合って、FORWARD_AS_ST_TLM 呼ばないとですよね、、

**Comment by meltingrabbit** [comment]
> sub OBC のテレメを DR に記録する場合って、FORWARD_AS_ST_TLM 呼ばないとですよね、

ちょうど気づいて，あ～～～
ってなってた．

**Comment by meltingrabbit** [comment]
やっぱ HK or High or Low は引数か？？

**Comment by meltingrabbit** [comment]
```
/**
 * @enum   TLM_MGR_BC_TYPE
 * @note   uint8_t を想定
 * @brief  BC のタイプ．これにて実行種別が変わる
 */
typedef enum
{
  TLM_MGR_BC_TYPE_MASTER,             //!< 全体の BC を deploy していく BC
  TLM_MGR_BC_TYPE_HK_TLM,             //!< HK テレメ (or 全系や system で入れておきたい tlm (1 Hz))
  TLM_MGR_BC_TYPE_HIGH_FREQ_TLM,      //!< User テレメ (1 Hz)
  TLM_MGR_BC_TYPE_LOW_FREQ_TLM        //!< User テレメ (1/10 Hz)
} TLM_MGR_BC_TYPE;
```

これを引数でとって， `TLM_MGR_BC_TYPE_MASTER` きたら弾けばいいけど，とはいえ，引数が 1, 2, 3だとコマンドファイルから分かりにくすぎるよね．

**Comment by chutaro** [comment]
- generate(apid, tlm_id)
- store(apid, tlm_id, partition)
- replay(partition)

にして、generate と store の内部で apid 見て、BCに登録するコマンド (generate or forword) × (RT or ST)を区別する、というのはどうでしょう？

**Comment by meltingrabbit** [comment]
自分自身のときにAPIDうちたくなくない？（一番使う and とくに 2nd obc）

**Comment by meltingrabbit** [comment]
議論ポイントは， HK or High or Low を引数にするか，コマンド名にするかな気がしている

**Comment by chutaro** [comment]
> やっぱ HK or High or Low は引数か？？
実装できるなら、個人的には引数にしたいです。実装案思いついているわけではないので恐縮ですが。

apid 打ちたくないはそうですよね、、

**Comment by meltingrabbit** [comment]
> 実装できるなら、個人的には引数にしたいです。実装案思いついているわけではないので恐縮ですが。

実装はできる．ポイントはコマンドファイルからあまりにもわかりにくいというところ
< これを引数でとって， TLM_MGR_BC_TYPE_MASTER きたら弾けばいいけど，とはいえ，引数が 1, 2, 3だとコマンドファイルから分かりにくすぎるよね．

**Comment by meltingrabbit** [comment]
まあ，引数でいくか！！！

で，CmdでCのenumが使えるように頑張る！！ということで．（？）

**Comment by chutaro** [comment]
> これを引数でとって， TLM_MGR_BC_TYPE_MASTER きたら弾けばいいけど，とはいえ，引数が 1, 2, 3だとコマンドファイルから分かりにくすぎるよね．

なるほどです、今読んでました。悩ましいですね。。コマンドファイルは妥協して、本当に嫌だったら運用SWで対応する、の方がいい気がします。c2aの他のコマンドでも引数 0,1,2 .. が分かりにくいのはあるので

**Comment by meltingrabbit** [comment]
OK~

コマンド名が決まったので，設計はfixしました．コマンド一覧とheaderだけまずpushするので，設計見てほしい，ってPRのほうでメンションします．

**Comment by chutaro** [comment]
ありがとうございます mm
