### ISSUE TITLE
doxygenの @file ，じつはファイル名書かなくていいのでは？

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#61]
## 概要
doxygenの @file ，じつはファイル名書かなくていいのでは？

## 詳細
参考： https://www.doxygen.nl/manual/commands.html#cmdfile

ちょっと英語がきちんと理解できてないかもしれないが，ファイル名を書かなくていい説がありそう．

## close条件
適切になったら．

**Comment by meltingrabbit** [comment]
https://github.com/ut-issl/c2a-reference/issues/1 が終わってからやったほうが良さそう．

**Comment by sksat** [comment]
cronでやるんだったら結局すぐに見えるわけでもないので依存関係無い気がする

**Comment by meltingrabbit** [comment]
ほんとに行けるか，手元でビルドするのがめんどいなぁ，っていう趣旨だった（Actions，手動でも発火できそうだったし）

**Comment by sksat** [comment]
あー，たしかに即座に更新したい時は`workflow_dispatch`とかで発射すればいいか
