### ISSUE TITLE
c89のgcc Wextra Warningに対応すると，あるマイコンIDEにてWarningが出てしまう

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#80]
## 概要
c89のgcc Wextra Warningに対応すると，あるマイコンIDEにてWarningが出てしまう

## 詳細
- https://github.com/ut-issl/c2a-core/pull/73 にて， `const uint32_t` などの返り値を `uint32_t` などにした
  - `warning: type qualifiers ignored on function return type [-Wignored-qualifiers]` が発生 
  - 右辺値にconstつけて返しても，値渡しなため意味がないから 
- 一方で，以下などでは，const構造体のメンバをconstなしで返している，として，あるマイコンIDEでは `C0008 (W) Conversion in return` を出してしまう．
  -  https://github.com/ut-issl/c2a-core/blob/1280836a5c6a6a5fc7a4fc8a5a9211134345b5b5/Drivers/Super/driver_super.c#L1513-L1516

## close条件
どちらの環境でもWarningがでなくなったら

## 備考
どうしようか．とりあえず，上の例だと，意味はないんだけど `(uint16_t)` とキャストさせる？

**Comment by sksat** [comment]
これ某IDEの方のwarningはコンパイラの実装が素朴なことによって出ているので微妙なんですよねえ．まあキャストかなあ．

**Comment by sksat** [comment]
あとGCCの方のwarningは組み込み型だからとかではなく，型修飾子である`const`を関数の戻り値に指定してもしょうがないからです．右辺値にconst付けてもしょうがない，といった方がいいかな．

**Comment by meltingrabbit** [comment]
> 右辺値にconst付けてもしょうがない

そうだね．ディスクリプション雑すぎたので直しておきます 🙏

**Comment by meltingrabbit** [comment]
> 某IDE

Warningメッセージでググると特定されるな笑

まあ，学会などでマイコン情報出してるので，問題ないと言えば問題はない．

**Comment by meltingrabbit** [comment]
これ，ちょっと気持ち悪いのが，

`const DS_StreamConfig* p_stream_config` なので，`p_stream_config->tx_frame_size_` の値そのものは const なので，これキャストすると，const キャストになっちゃうんだよね．

**Comment by meltingrabbit** [comment]
まだでてる．

- [ ] common_tlm_cmd_packet_util
- [ ] command_analyze

**Comment by meltingrabbit** [comment]
一旦きえた？

ひとまず様子見

**Comment by meltingrabbit** [comment]
また出たらissueをきるとして，close
