### ISSUE TITLE
無名unionを消す，無名unionがC89 CIを通過してしまう

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#94]
## 概要
無名unionを消す，無名unionがC89 CIを通過してしまう

## 詳細
これ

https://github.com/ut-issl/c2a-core/blob/8d6f9a4e92f362fdc997b0f4242adfecb74d57cd/CmdTlm/command_analyze.h#L36-L47

これを通過してしまった．
https://github.com/ut-issl/c2a-core/blob/develop/.github/workflows/build_as_c89.yml

## close条件
- [x] 無名union部分は直す
- [x] CIも改善する
- [x] C89対応CIも通るようにする

**Comment by meltingrabbit** [comment]
@sksat CIの方，見てもらってもいいかな？

**Comment by sksat** [comment]
無名構造体/共用体，C11なんですね...

**Comment by meltingrabbit** [comment]
https://github.com/ut-issl/c2a-core/pull/104 がマージされ次第，最後のC89対応かなぁ．

**Comment by meltingrabbit** [comment]
とはいえ，`BC_DEFAULT_ID` は自動生成なので，ここは tlm cmd code generator側も修正しないとダメそうだ．

**Comment by sksat** [comment]
@meltingrabbit これもう閉じられるのでは

**Comment by meltingrabbit** [comment]
C89 CI通してから？

**Comment by sksat** [comment]
あと出てるの普通のワーニングなのでスコープ違うかなとは思いつつ，まあそうか

**Comment by meltingrabbit** [comment]
完了
