### ISSUE TITLE
CAのWarning消し

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-core#97]
## 概要
CAのWarning消し

## 詳細
- https://github.com/ut-issl/c2a-core/blob/014a8b340ef2a2d0382667074b4f6b0f8c6651ec/CmdTlm/command_analyze.c#L142
  - 引数u8なので，-1すると汎整数拡張
- https://github.com/ut-issl/c2a-core/blob/014a8b340ef2a2d0382667074b4f6b0f8c6651ec/CmdTlm/command_analyze.c#L170
-  ret は u16 

## close条件
直したら

**Comment by yngyu** [comment]
https://github.com/ut-issl/c2a-core/pull/115  
マージされたのでclose
